
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 193
#define YY_END_OF_BUFFER 194
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[731] =
    {   0,
        0,    0,  194,  192,  191,  190,  179,  184,  182,  183,
      181,  192,  165,  171,  174,  169,  157,  167,  158,  173,
      148,  156,  172,  166,  160,  162,  185,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  163,
      170,  177,  187,  180,  178,  191,  154,    0,    0,    0,
        0,    0,  186,  175,  176,  159,  188,    0,  148,  155,
      164,  168,  161,  147,  147,  147,  147,  147,  147,  147,
       88,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,   41,  147,  147,  147,  147,  147,

      147,  147,  147,  147,   51,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,   56,  147,    9,
      147,   57,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
       68,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,    0,    0,    0,  189,  149,  147,  147,  147,
       36,  147,  147,  146,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,   40,  147,  147,  147,  147,   44,  147,  147,  147,
      147,  147,  122,  147,  147,   47,  147,  147,  147,  147,

      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
       53,  147,  147,   34,   54,  147,  147,   55,  147,  147,
      147,  147,  147,   26,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,   66,   13,  147,   14,  147,  147,  147,  147,
      147,  147,  147,  147,  147,   30,  147,  147,  147,  147,
       71,  147,  147,  147,  147,  147,  147,   18,  153,  152,
      151,    0,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,   98,  147,   38,  147,  103,  147,   94,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,   43,

      147,   32,  147,  147,  147,  147,   61,  147,  147,  147,
       50,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  126,  127,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  136,  145,  147,  147,  147,
      147,  147,  147,  147,  147,   12,  147,  147,  147,  147,
      147,  147,  147,   67,  147,   35,   69,   16,  147,   17,
      147,  147,  147,  147,   73,  101,  147,    0,  147,  147,
      147,  116,  147,   37,  147,  147,   60,  147,  147,  118,
       19,   39,  147,  147,  147,  147,  147,  147,  147,  147,

      147,  147,  147,  147,  147,  147,   33,  123,  147,  147,
      147,  147,  147,  124,  147,  147,  147,  100,  147,  147,
       52,  147,  125,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  106,  147,
      147,  147,  147,  147,  147,   97,   28,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,   70,  147,  147,   72,  147,
      147,  143,  150,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,   91,
       42,  147,   20,  121,  147,   45,  147,  147,  147,  147,

      147,  147,  147,  147,    6,  147,  147,  147,  147,  147,
      147,  147,  147,    8,  147,  147,  147,  147,  147,  147,
      147,   59,  131,  147,  147,  147,  147,  147,  134,  147,
      147,   89,   64,  147,  147,   65,  147,  147,  147,  147,
      147,   90,  147,  147,  147,   85,   15,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  109,  147,  147,
      102,  147,  147,  147,  119,  147,  120,  147,  147,   31,
      112,   21,  147,  147,  147,   23,   48,  147,  147,  147,
      147,  147,  144,  147,   25,   99,  147,   87,  147,  147,
      147,  147,  147,  147,  147,  147,   77,  132,  147,   63,

      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  140,  147,  114,  141,  147,  110,  142,
      147,    1,  115,  147,  147,  147,  107,  147,   79,   93,
      147,  147,   92,   46,  147,   49,  147,  147,  147,  147,
      147,  105,  147,  147,  147,  147,   10,  147,  113,  130,
      147,   27,  147,  147,   82,  137,  147,   78,   76,  147,
      138,   95,   96,  147,  147,  104,  147,   80,  117,  111,
      147,  147,  147,  147,  147,  147,    5,  147,    7,   84,
      147,  147,  147,   58,   62,  133,  135,  147,  147,  139,
       29,   83,  147,    3,  147,  147,  147,  147,   86,  147,

      147,  129,  108,  147,  147,    2,  147,  147,  147,  147,
      147,  147,   11,  147,  147,   22,  147,  147,  147,  128,
      147,   81,    4,  147,  147,  147,   74,   24,   75,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   21,   20,   22,   20,   23,   24,   25,   26,   27,
       28,   29,    1,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,    1,   58,   59,   60,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   61,   62,    1,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    3,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[735] =
    {   0,
        0,    0,  822,  823,  819,  823,  823,   46,    0,   53,
       55,  811,  807,  823,  806,  823,  823,  788,  800,  798,
       62,  786,  823,   59,  823,  785,  823,   57,   55,   78,
       58,   50,   80,  767,    0,   78,   87,   82,   99,  101,
      108,  758,   67,  119,  122,   91,   97,  127,  765,  823,
      823,  823,  823,  823,  823,  807,  160,  792,  155,  169,
      798,  797,  823,  823,  823,  823,  823,  174,  183,  823,
      823,  823,  823,    0,  756,  770,  764,  112,  754,   99,
        0,  751,  763,  754,  748,   47,  762,  765,  764,  165,
      748,  745,  119,  161,  161,  748,  742,  756,  178,  173,

      174,  741,  744,  737,    0,  177,  188,  754,  753,  187,
      735,  749,  739,  194,  739,  195,  740,    0,  198,    0,
      744,    0,  740,  727,  741,  201,  737,  196,  742,  728,
      733,  209,  735,  201,  212,  726,  738,  732,  218,  128,
        0,  198,  721,  220,  731,  717,  716,  724,  227,  714,
      722,  712,    0,  218,  253,  750,  260,  217,  710,  726,
        0,  717,  724,    0,  719,  708,  713,  709,  715,  715,
      713,  714,  698,  696,  698,  215,  709,  694,  710,  690,
      693,    0,  706,  693,  705,  700,    0,  699,  683,  687,
      696,  681,  710,  693,  696,  673,  692,  679,  688,  680,

      686,  685,  669,  679,  254,  682,  668,  684,  677,  664,
        0,  677,  663,    0,    0,  675,  659,    0,  673,  671,
      654,  657,  669,    0,  655,  661,  668,  669,  647,  253,
      656,  649,  647,  251,  650,  655,  649,  657,  640,  249,
      655,  653,    0,    0,  640,    0,  650,  644,  635,  651,
      635,  643,  637,  645,  644,    0,  643,  627,  637,  626,
      635,  623,  630,  636,  632,  635,  618,    0,    0,  250,
      286,  283,  625,  618,  630,  615,  614,  607,  618,  617,
      615,  623,    0,  618,    0,  614,    0,  606,    0,  604,
      622,  617,  616,  599,  601,  252,  606,  597,  603,    0,

      599,    0,  596,  265,  608,  620,    0,  599,  609,  589,
        0,  595,  602,  582,  587,  595,  589,  611,  263,  589,
      599,  587,  147,  597,    0,    0,  591,  595,  592,  578,
      592,  591,  573,  268,  283,  589,  571,  587,  582,  568,
      580,  579,  574,  578,  576,  565,  588,  560,  558,  556,
      574,  565,  569,  551,  568,    0,  550,  557,  556,  561,
      565,  560,  550,    0,  562,    0,    0,    0,  550,    0,
      560,  539,  554,  268,    0,    0,  553,  301,  536,  555,
      536,    0,  534,    0,  551,  551,    0,  550,  536,    0,
        0,  531,  539,  544,  532,  533,  523,  529,  523,  536,

      525,  530,  518,  517,  532,  521,    0,    0,  273,  516,
      524,  527,  518,    0,  521,  528,  523,    0,  522,  520,
        0,  507,    0,  510,  508,  515,  520,  517,  499,  515,
      499,  496,  492,  499,  504,  505,  507,  498,    0,  489,
      504,  506,  488,  502,  293,    0,    0,  490,  510,  498,
      481,  482,  479,  480,  492,  478,  494,  485,  488,  483,
      479,  478,  485,  481,  483,    0,  472,  484,    0,  476,
      463,  285,  313,  462,  478,  461,  461,  466,  457,  462,
      474,  453,  459,  460,  468,  450,  466,  448,  462,    0,
        0,  463,    0,  446,  459,  462,  436,  436,  456,  444,

      444,  452,  436,  443,    0,  436,  452,  427,  431,  432,
      444,  427,  436,    0,  443,  436,  429,  434,  441,  437,
      435,    0,    0,  434,  417,  424,  416,  415,    0,  426,
      421,    0,    0,  427,  416,    0,  425,  415,  425,  415,
      412,    0,  411,  409,  411,    0,    0,  400,  401,  408,
      418,  400,  403,  402,  410,  394,  398,    0,  407,  406,
        0,  398,  406,  389,    0,  382,    0,  386,  400,    0,
        0,    0,  400,  391,  401,    0,    0,  387,  380,  385,
      393,  388,    0,  393,    0,    0,  391,    0,  382,  387,
      391,  390,  372,  370,  384,  382,    0,    0,  368,    0,

      360,  379,  378,  357,  363,  376,  360,  358,  372,  364,
      355,  354,  372,    0,  371,    0,    0,  353,    0,    0,
      358,    0,    0,  363,  350,  363,    0,  346,    0,    0,
      350,  346,    0,    0,  343,    0,  361,  341,  356,  333,
      353,    0,  337,  338,  343,  340,    0,  348,    0,    0,
      347,    0,  347,  346,    0,    0,  328,    0,    0,  329,
        0,    0,    0,  327,  328,    0,  320,    0,    0,    0,
      329,  325,  336,  332,  320,  297,    0,  338,    0,    0,
      337,  325,  316,    0,    0,    0,    0,  332,  314,    0,
        0,    0,  315,    0,  331,  316,  321,  309,    0,  308,

      314,    0,    0,  321,  307,    0,  321,  309,  307,  306,
      305,  308,    0,  302,  305,    0,  295,  293,  284,    0,
      258,    0,    0,  248,  243,  202,    0,    0,    0,  823,
      113,  346,  348,   77
    } ;

static yyconst flex_int16_t yy_def[735] =
    {   0,
      730,    1,  730,  730,  730,  730,  730,  730,  731,  730,
      730,  732,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  730,
      730,  730,  730,  730,  730,  730,  730,  731,  730,  730,
      732,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,

      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  734,  730,  730,  730,  730,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,

      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  734,  730,
      730,  730,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,

      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  730,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,

      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  730,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,

      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,

      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,

      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  733,  733,  733,    0,
      730,  730,  730,  730
    } ;

static yyconst flex_int16_t yy_nxt[887] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       21,   21,   21,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   35,
       35,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   35,   35,   50,   51,   52,    4,
       53,   54,   55,   57,   57,   57,   57,   57,   57,   57,
       59,   59,   60,   60,   60,   60,   60,   68,  269,   69,
       69,   69,   69,   69,   69,   69,   71,   72,   75,   83,
       76,   97,   93,   98,  170,  171,   94,  131,   77,   84,

       78,  132,   95,   99,   79,   80,   81,   82,   86,   85,
      100,   87,   96,  105,   58,   88,  111,  108,  101,   89,
      106,  107,   90,   91,  102,  109,  112,  146,   92,  113,
      103,  110,  117,  114,  144,  147,  118,  115,  126,  145,
      127,  164,  119,  116,  120,  161,  121,  165,  122,  133,
      123,  124,  125,  134,  179,  128,  135,  136,  129,  140,
      162,  137,  253,  138,  148,  149,  141,  180,  139,  142,
      154,  150,   59,   59,  151,  254,  143,   57,   57,   57,
       57,   57,   57,   57,  155,  424,   60,   60,   60,   60,
       60,  157,  157,  157,  157,  157,  157,  157,   68,  425,

       69,   69,   69,   69,   69,   69,   69,  175,  176,  181,
      188,  183,  182,  184,  192,  194,  189,  195,  199,  208,
      193,  201,  200,  190,  213,  202,  203,  191,  216,  204,
      209,  220,  221,  226,  229,  270,  270,  205,  729,  234,
      230,  235,  242,  217,  218,  236,  214,  237,  255,  227,
      243,  250,  256,  244,  238,  239,  245,  240,  258,  246,
      264,  273,  251,  290,  291,  252,  274,  270,  270,  259,
      271,  271,  271,  271,  271,  318,  265,  157,  157,  157,
      157,  157,  157,  157,  346,  339,  728,  353,  319,  340,
      398,  727,  347,  354,  272,  378,  399,  378,  341,  419,

      470,  726,  342,  271,  271,  271,  271,  271,  405,  434,
      420,  497,  406,  436,  498,  435,  471,  437,  473,  473,
      473,  473,  473,  473,  473,  529,  553,  698,  725,  554,
      473,  473,  473,  473,  473,  473,  473,  724,  723,  722,
      721,  530,  720,  719,  718,  699,   61,   61,   61,   74,
       74,  717,  716,  715,  714,  713,  712,  711,  710,  709,
      708,  707,  706,  705,  704,  703,  702,  701,  700,  697,
      696,  695,  694,  693,  692,  691,  690,  689,  688,  687,
      686,  685,  684,  683,  682,  681,  680,  679,  678,  677,
      676,  675,  674,  673,  672,  671,  670,  669,  668,  667,

      666,  665,  664,  663,  662,  661,  660,  659,  658,  657,
      656,  655,  654,  653,  652,  651,  650,  649,  648,  647,
      646,  645,  644,  643,  642,  641,  640,  639,  638,  637,
      636,  635,  634,  633,  632,  631,  630,  629,  628,  627,
      626,  625,  624,  623,  622,  621,  620,  619,  618,  617,
      616,  615,  614,  613,  612,  611,  610,  609,  608,  607,
      606,  605,  604,  603,  602,  601,  600,  599,  598,  597,
      596,  595,  594,  593,  592,  591,  590,  589,  588,  587,
      586,  585,  584,  583,  582,  581,  580,  579,  578,  577,
      576,  575,  574,  573,  572,  571,  570,  569,  568,  567,

      566,  565,  564,  563,  562,  561,  560,  559,  558,  557,
      556,  555,  552,  551,  550,  549,  548,  547,  546,  545,
      544,  543,  542,  541,  540,  539,  538,  537,  536,  535,
      534,  533,  532,  531,  528,  527,  526,  525,  524,  523,
      522,  521,  520,  519,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,
      502,  501,  500,  499,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  472,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,

      457,  456,  455,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      433,  432,  431,  430,  429,  428,  427,  426,  423,  422,
      421,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  404,  403,  402,  401,  400,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      352,  351,  350,  349,  348,  345,  344,  343,  338,  337,

      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  317,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,   61,  268,
      267,  266,  263,  262,  261,  260,  257,  249,  248,  247,
      241,  233,  232,  231,  228,  225,  224,  223,  222,  219,
      215,  212,  211,  210,  207,  206,  198,  197,  196,  187,
      186,  185,  178,  177,  174,  173,  172,  169,  168,  167,

      166,  163,  160,  159,  158,   61,  156,  153,   56,  152,
      130,  104,   73,   70,   67,   66,   65,   64,   63,   62,
       56,  730,    3,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730
    } ;

static yyconst flex_int16_t yy_chk[887] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    8,    8,    8,    8,    8,    8,
       10,   10,   11,   11,   11,   11,   11,   21,  734,   21,
       21,   21,   21,   21,   21,   21,   24,   24,   28,   29,
       28,   32,   31,   32,   86,   86,   31,   43,   28,   29,

       28,   43,   31,   32,   28,   28,   28,   28,   30,   29,
       33,   30,   31,   36,  731,   30,   38,   37,   33,   30,
       36,   36,   30,   30,   33,   37,   38,   47,   30,   39,
       33,   37,   40,   39,   46,   47,   40,   39,   41,   46,
       41,   80,   40,   39,   40,   78,   40,   80,   40,   44,
       40,   40,   40,   44,   93,   41,   44,   44,   41,   45,
       78,   44,  140,   44,   48,   48,   45,   93,   44,   45,
       59,   48,   59,   59,   48,  140,   45,   57,   57,   57,
       57,   57,   57,   57,   60,  323,   60,   60,   60,   60,
       60,   68,   68,   68,   68,   68,   68,   68,   69,  323,

       69,   69,   69,   69,   69,   69,   69,   90,   90,   94,
       99,   95,   94,   95,  100,  101,   99,  101,  106,  110,
      100,  107,  106,   99,  114,  107,  107,   99,  116,  107,
      110,  119,  119,  126,  128,  154,  154,  107,  726,  132,
      128,  132,  134,  116,  116,  132,  114,  132,  142,  126,
      134,  139,  142,  135,  132,  132,  135,  132,  144,  135,
      149,  158,  139,  176,  176,  139,  158,  270,  270,  144,
      155,  155,  155,  155,  155,  205,  149,  157,  157,  157,
      157,  157,  157,  157,  234,  230,  725,  240,  205,  230,
      296,  724,  234,  240,  157,  272,  296,  272,  230,  319,

      374,  721,  230,  271,  271,  271,  271,  271,  304,  334,
      319,  409,  304,  335,  409,  334,  374,  335,  378,  378,
      378,  378,  378,  378,  378,  445,  472,  676,  719,  472,
      473,  473,  473,  473,  473,  473,  473,  718,  717,  715,
      714,  445,  712,  711,  710,  676,  732,  732,  732,  733,
      733,  709,  708,  707,  705,  704,  701,  700,  698,  697,
      696,  695,  693,  689,  688,  683,  682,  681,  678,  675,
      674,  673,  672,  671,  667,  665,  664,  660,  657,  654,
      653,  651,  648,  646,  645,  644,  643,  641,  640,  639,
      638,  637,  635,  632,  631,  628,  626,  625,  624,  621,

      618,  615,  613,  612,  611,  610,  609,  608,  607,  606,
      605,  604,  603,  602,  601,  599,  596,  595,  594,  593,
      592,  591,  590,  589,  587,  584,  582,  581,  580,  579,
      578,  575,  574,  573,  569,  568,  566,  564,  563,  562,
      560,  559,  557,  556,  555,  554,  553,  552,  551,  550,
      549,  548,  545,  544,  543,  541,  540,  539,  538,  537,
      535,  534,  531,  530,  528,  527,  526,  525,  524,  521,
      520,  519,  518,  517,  516,  515,  513,  512,  511,  510,
      509,  508,  507,  506,  504,  503,  502,  501,  500,  499,
      498,  497,  496,  495,  494,  492,  489,  488,  487,  486,

      485,  484,  483,  482,  481,  480,  479,  478,  477,  476,
      475,  474,  471,  470,  468,  467,  465,  464,  463,  462,
      461,  460,  459,  458,  457,  456,  455,  454,  453,  452,
      451,  450,  449,  448,  444,  443,  442,  441,  440,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  422,  420,  419,  417,  416,  415,
      413,  412,  411,  410,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  392,  389,
      388,  386,  385,  383,  381,  380,  379,  377,  373,  372,
      371,  369,  365,  363,  362,  361,  360,  359,  358,  357,

      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      333,  332,  331,  330,  329,  328,  327,  324,  322,  321,
      320,  318,  317,  316,  315,  314,  313,  312,  310,  309,
      308,  306,  305,  303,  301,  299,  298,  297,  295,  294,
      293,  292,  291,  290,  288,  286,  284,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  245,  242,  241,
      239,  238,  237,  236,  235,  233,  232,  231,  229,  228,

      227,  226,  225,  223,  222,  221,  220,  219,  217,  216,
      213,  212,  210,  209,  208,  207,  206,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  186,  185,  184,  183,  181,  180,
      179,  178,  177,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  163,  162,  160,  159,  156,  152,
      151,  150,  148,  147,  146,  145,  143,  138,  137,  136,
      133,  131,  130,  129,  127,  125,  124,  123,  121,  117,
      115,  113,  112,  111,  109,  108,  104,  103,  102,   98,
       97,   96,   92,   91,   89,   88,   87,   85,   84,   83,

       82,   79,   77,   76,   75,   62,   61,   58,   56,   49,
       42,   34,   26,   22,   20,   19,   18,   15,   13,   12,
        5,    3,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexicalAnalyzer.l"
#line 2 "lexicalAnalyzer.l"
/* This program identifies tokens from a 
 * valid pascal program. Note that pascal is
 * case insensitive for identifiers and keywords.
 * http://www.freepascal.org/ is the reference used.
*/
#include <stdarg.h>
#include "Definitions.h"
#include "y.tab.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void yyerror(char * error);
int line_number =1;
unsigned int curScopeId = 0;
unsigned int tempId = 1;
unsigned int labelId = 1;
unsigned int quadId = 0;
int tempArray[1000];
FILE *data,*text;
char tempName[256];
int ifFlag = 0;

int yywrap(void){
return 1;}

#line 922 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 76 "lexicalAnalyzer.l"


#line 1112 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 731 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 823 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 78 "lexicalAnalyzer.l"
return(ABSOLUTE);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 79 "lexicalAnalyzer.l"
{  curScopeId++; Push(&scopeStack,curScopeId);return(CONSTRUCT);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 80 "lexicalAnalyzer.l"
{    curScopeId++; Push(&scopeStack,curScopeId);return(DESTRUCT);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "lexicalAnalyzer.l"
return(IMPLEMENT);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 82 "lexicalAnalyzer.l"
return(INHERITED);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 83 "lexicalAnalyzer.l"
return(INLINE);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 84 "lexicalAnalyzer.l"
return(INTERFACE);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 85 "lexicalAnalyzer.l"
{ curScopeId++; Push(&scopeStack,curScopeId);/*scopeStack = (scopeStack << SCOPE_ID_SIZE) | curScopeId;*/ return(OBJ);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 86 "lexicalAnalyzer.l"
return(ON);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 87 "lexicalAnalyzer.l"
return(OP);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 88 "lexicalAnalyzer.l"
return(REINTRO);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 89 "lexicalAnalyzer.l"
return(SELF);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 90 "lexicalAnalyzer.l"
return(SHL);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 91 "lexicalAnalyzer.l"
return(SHR);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 92 "lexicalAnalyzer.l"
return(STRING);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 93 "lexicalAnalyzer.l"
{ curScopeId++; Push(&scopeStack,curScopeId);/*scopeStack = (scopeStack << SCOPE_ID_SIZE) | curScopeId;*/ return(UNIT);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 94 "lexicalAnalyzer.l"
return(USES);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 95 "lexicalAnalyzer.l"
return(XOR);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 96 "lexicalAnalyzer.l"
{ curScopeId++; Push(&scopeStack,curScopeId);return(CLASS);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 97 "lexicalAnalyzer.l"
return(EXCEPT);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 98 "lexicalAnalyzer.l"
return(EXPORTS);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 99 "lexicalAnalyzer.l"
return(FINALIZATION);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 100 "lexicalAnalyzer.l"
return(FINALLY);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 101 "lexicalAnalyzer.l"
return(INITIALIZATION);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 102 "lexicalAnalyzer.l"
{ curScopeId++; Push(&scopeStack,curScopeId);return(LIBRARY);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 103 "lexicalAnalyzer.l"
return(OUT);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 104 "lexicalAnalyzer.l"
return(PROPERTY);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 105 "lexicalAnalyzer.l"
return(RAISE);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 106 "lexicalAnalyzer.l"
return(THREADVAR);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 107 "lexicalAnalyzer.l"
return(TRY);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 108 "lexicalAnalyzer.l"
return(DISPOSE);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 109 "lexicalAnalyzer.l"
return(EXIT);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 110 "lexicalAnalyzer.l"
return(PFALSE);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 111 "lexicalAnalyzer.l"
return(NEW);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 112 "lexicalAnalyzer.l"
return(PTRUE);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 113 "lexicalAnalyzer.l"
{return(AND);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 114 "lexicalAnalyzer.l"
return(ARRAY);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 115 "lexicalAnalyzer.l"
return(CASE);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 116 "lexicalAnalyzer.l"
return(CONST);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 117 "lexicalAnalyzer.l"
return(DIV);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 118 "lexicalAnalyzer.l"
return(DO);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 119 "lexicalAnalyzer.l"
{return(DOWNTO);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 120 "lexicalAnalyzer.l"
return(ELSE);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 121 "lexicalAnalyzer.l"
return(END);
	YY_BREAK
case 45:
#line 123 "lexicalAnalyzer.l"
case 46:
YY_RULE_SETUP
#line 123 "lexicalAnalyzer.l"
return(EXTERNAL);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 124 "lexicalAnalyzer.l"
{ ifFlag = 1;return(FOR);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 125 "lexicalAnalyzer.l"
return(FORWARD);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 126 "lexicalAnalyzer.l"
{return(FUNC);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 127 "lexicalAnalyzer.l"
return(GOTO);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 128 "lexicalAnalyzer.l"
{ifFlag = 1; return(IF);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "lexicalAnalyzer.l"
return(LABEL);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "lexicalAnalyzer.l"
{return(MOD);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 131 "lexicalAnalyzer.l"
return(NIL);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 132 "lexicalAnalyzer.l"
return(NOT);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 133 "lexicalAnalyzer.l"
return(OF);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 134 "lexicalAnalyzer.l"
{return(OR);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 135 "lexicalAnalyzer.l"
return(OTHERWISE);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 136 "lexicalAnalyzer.l"
return(PACKED);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 137 "lexicalAnalyzer.l"
return(PBEGIN);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 138 "lexicalAnalyzer.l"
return(PFILE);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 139 "lexicalAnalyzer.l"
{ return(PROCEDURE); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 140 "lexicalAnalyzer.l"
{ curScopeId++; Push(&scopeStack,curScopeId);return(PROGRAM);  }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 141 "lexicalAnalyzer.l"
{curScopeId++; Push(&scopeStack,curScopeId); return(RECORD);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 142 "lexicalAnalyzer.l"
return(REPEAT);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 143 "lexicalAnalyzer.l"
return(SET);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 144 "lexicalAnalyzer.l"
return(THEN);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 145 "lexicalAnalyzer.l"
{ return(TO);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 146 "lexicalAnalyzer.l"
return(TYPE);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 147 "lexicalAnalyzer.l"
{ ifFlag = 1; return(UNTIL);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 148 "lexicalAnalyzer.l"
return(VAR);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 149 "lexicalAnalyzer.l"
{ifFlag = 1; return(WHILE);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 150 "lexicalAnalyzer.l"
return(WITH);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 152 "lexicalAnalyzer.l"
return(IMPLEMENTATION );
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 153 "lexicalAnalyzer.l"
return(RESOURCESTRING);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 154 "lexicalAnalyzer.l"
return(RESIDENT);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 155 "lexicalAnalyzer.l"
return(PACKAGE);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 156 "lexicalAnalyzer.l"
return(REQUIRES);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 157 "lexicalAnalyzer.l"
return(CONTAINS);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 158 "lexicalAnalyzer.l"
return(ADDROF);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 159 "lexicalAnalyzer.l"
return(DISPINTERFACE);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 160 "lexicalAnalyzer.l"
return(READONLY);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 161 "lexicalAnalyzer.l"
return(WRITEONLY);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 162 "lexicalAnalyzer.l"
return(NODEFAULT);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 163 "lexicalAnalyzer.l"
return(store_argumentD);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 164 "lexicalAnalyzer.l"
return(IMPLEMENTS);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 165 "lexicalAnalyzer.l"
return(MESSAGE);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 166 "lexicalAnalyzer.l"
return(AT);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 167 "lexicalAnalyzer.l"
return(REAL48);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 168 "lexicalAnalyzer.l"
return(SINGLE);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 169 "lexicalAnalyzer.l"
return(DOUBLE);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 170 "lexicalAnalyzer.l"
return(EXTENDED);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 171 "lexicalAnalyzer.l"
return(CURRENCY);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 172 "lexicalAnalyzer.l"
return(COMP);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 173 "lexicalAnalyzer.l"
return(SHORTINT);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 174 "lexicalAnalyzer.l"
return(SMALLINT);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 175 "lexicalAnalyzer.l"
return(QWORD);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 176 "lexicalAnalyzer.l"
return(BYTE);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 177 "lexicalAnalyzer.l"
return(LONGINT);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 178 "lexicalAnalyzer.l"
return(INT64);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 179 "lexicalAnalyzer.l"
return(WORD);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 180 "lexicalAnalyzer.l"
return(BOOLEAN);
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 181 "lexicalAnalyzer.l"
return(CHAR);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 182 "lexicalAnalyzer.l"
return(WIDECHAR);
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 183 "lexicalAnalyzer.l"
return(LONGWORD);
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 184 "lexicalAnalyzer.l"
return(PCHAR);
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 185 "lexicalAnalyzer.l"
return(CARDINAL);
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 186 "lexicalAnalyzer.l"
return(OLEVARIANT);
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 187 "lexicalAnalyzer.l"
return(ANSISTR);	
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 188 "lexicalAnalyzer.l"
return(WIDESTR);
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 189 "lexicalAnalyzer.l"
return(AUTOMATED);
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 190 "lexicalAnalyzer.l"
return(DYNAMIC);
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 191 "lexicalAnalyzer.l"
return(OVERLOAD);
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 192 "lexicalAnalyzer.l"
return(VARIANT);
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 194 "lexicalAnalyzer.l"
return(ABSTRACT);
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 195 "lexicalAnalyzer.l"
return(ALIAS);
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 196 "lexicalAnalyzer.l"
return(ASSEMBLER);
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 197 "lexicalAnalyzer.l"
return(CDECL);
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 198 "lexicalAnalyzer.l"
return(CPPDECL);
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 199 "lexicalAnalyzer.l"
return(DEFAULT);
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 200 "lexicalAnalyzer.l"
return(EXPORT);
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 201 "lexicalAnalyzer.l"
return(FAR);
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 202 "lexicalAnalyzer.l"
return(FAR16);
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 203 "lexicalAnalyzer.l"
return(INDEX);
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 204 "lexicalAnalyzer.l"
return(LOCAL);
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 205 "lexicalAnalyzer.l"
return(NAME);
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 206 "lexicalAnalyzer.l"
return(NEAR);
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 207 "lexicalAnalyzer.l"
return(NOSTACKFRAME);
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 208 "lexicalAnalyzer.l"
return(OLDFPCCALL);
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 209 "lexicalAnalyzer.l"
return(OVERRIDE);
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 210 "lexicalAnalyzer.l"
return(PASCAL);
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 211 "lexicalAnalyzer.l"
return(PRIVATE);
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 212 "lexicalAnalyzer.l"
return(PROTECTED);
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 213 "lexicalAnalyzer.l"
return(PUBLIC);
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 214 "lexicalAnalyzer.l"
return(PUBLISHED);
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 215 "lexicalAnalyzer.l"
return(READ);
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 216 "lexicalAnalyzer.l"
return(REGISTER);
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 217 "lexicalAnalyzer.l"
return(SAFECALL);
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 218 "lexicalAnalyzer.l"
return(SOFTFLOAT);
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 219 "lexicalAnalyzer.l"
return(STDCALL);
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 220 "lexicalAnalyzer.l"
return(VIRTUAL);
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 221 "lexicalAnalyzer.l"
return(WRITELN);
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 222 "lexicalAnalyzer.l"
return(WRITE);
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 223 "lexicalAnalyzer.l"
return(INTEGER);
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 224 "lexicalAnalyzer.l"
return(REALS);
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 226 "lexicalAnalyzer.l"
{ register int c;
     while ((c = input()))
     {
      if (c == 'E' || c == 'e') {
		c = input();
		if (c == 'N' || c == 'n') {
			c = input();
			if (c == 'D' || c == 'd') {
				return(ASMBODY);
				break;
			}
		}
	}
      else if (c == '\n') {
       line_number++;
	
      }
     }
    }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 246 "lexicalAnalyzer.l"
{ strcpy(yylval.name,yytext); /*NewEntry(yytext,IDENT,line_number,&table[hashKey(yytext)],scopeStack);*/ return(IDENT); }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 247 "lexicalAnalyzer.l"
{  yylval.ival = atoi(yytext);return(INT); }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 248 "lexicalAnalyzer.l"
{   yylval.dval = atof(yytext); return(FLOAT); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 249 "lexicalAnalyzer.l"
{ yylval.dval = atof(yytext); return(REAL); }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 250 "lexicalAnalyzer.l"
{  strcpy(yylval.name,yytext); return(OCTAL); }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 251 "lexicalAnalyzer.l"
{ strcpy(yylval.name,yytext);return(BINARY); }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 252 "lexicalAnalyzer.l"
{  strcpy(yylval.name,yytext);return(HEXA); }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 254 "lexicalAnalyzer.l"
return(ASCIICHAR);
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 255 "lexicalAnalyzer.l"
{ return(ASSIGN);}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 256 "lexicalAnalyzer.l"
return(COLON);
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 257 "lexicalAnalyzer.l"
return(COMMA);
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 258 "lexicalAnalyzer.l"
return(DOT);
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 259 "lexicalAnalyzer.l"
return(DOTDOT);
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 260 "lexicalAnalyzer.l"
{return(EQUAL);}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 261 "lexicalAnalyzer.l"
{return(GE);}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 262 "lexicalAnalyzer.l"
{return(GT);}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 263 "lexicalAnalyzer.l"
return(LSQBRACK);
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 264 "lexicalAnalyzer.l"
{return(LE);}
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 265 "lexicalAnalyzer.l"
return(LPAREN);
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 266 "lexicalAnalyzer.l"
{return(LT);}
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 267 "lexicalAnalyzer.l"
{return(MINUS);}
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 268 "lexicalAnalyzer.l"
{return(NOTEQUAL);}
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 269 "lexicalAnalyzer.l"
{return(PLUS);}
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 270 "lexicalAnalyzer.l"
return(RSQBRACK);
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 271 "lexicalAnalyzer.l"
return(RPAREN);
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 272 "lexicalAnalyzer.l"
return(SEMICOLON);
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 273 "lexicalAnalyzer.l"
{return(SLASH);}
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 274 "lexicalAnalyzer.l"
{return(STAR);}
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 275 "lexicalAnalyzer.l"
{return(STARSTAR);}
	YY_BREAK
case 176:
#line 277 "lexicalAnalyzer.l"
case 177:
YY_RULE_SETUP
#line 277 "lexicalAnalyzer.l"
return(UPARROW);
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 278 "lexicalAnalyzer.l"
return(BITNOT);
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 279 "lexicalAnalyzer.l"
return(EXCLA);
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 280 "lexicalAnalyzer.l"
return(BITOR);
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 281 "lexicalAnalyzer.l"
return(BITAND);
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 282 "lexicalAnalyzer.l"
return(DOLLAR);
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 283 "lexicalAnalyzer.l"
return(PERCENT);
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 284 "lexicalAnalyzer.l"
return(HASH);
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 285 "lexicalAnalyzer.l"
return(ADDROF);
	YY_BREAK
case 186:
#line 288 "lexicalAnalyzer.l"
case 187:
#line 289 "lexicalAnalyzer.l"
case 188:
YY_RULE_SETUP
#line 289 "lexicalAnalyzer.l"
{ register int c;
     while ((c = input()))
     {
      if (c == '}' && yytext[0] == '{')
       break;
      else if (c == '*' && yytext[0] != '{')
      {
       if ((c = input()) == ')')
        break;
       else
        unput (c);
      }
      else if (c == '\n') {
       line_number++;
	if(yytext[0] == '/')
		break;
      }
     }
    }
	YY_BREAK
case 189:
/* rule 189 can match eol */
YY_RULE_SETUP
#line 310 "lexicalAnalyzer.l"
{  strcpy(yylval.name,yytext);return(CHAR_STRING);}
	YY_BREAK
case 190:
/* rule 190 can match eol */
YY_RULE_SETUP
#line 313 "lexicalAnalyzer.l"
line_number++;
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 314 "lexicalAnalyzer.l"
/* ignore */
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 316 "lexicalAnalyzer.l"
{printf("\n ** Illegal Character %c at line number %d ** \n",yytext[0],line_number);}
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 318 "lexicalAnalyzer.l"
ECHO;
	YY_BREAK
#line 2186 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 731 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 731 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 730);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 318 "lexicalAnalyzer.l"



